name: 🐛 Bug
description: File a bug
title: "BUG: <Enter title here, leaving the 'bug: ' prefix>"
labels: ["bug"]

body:
  - type: markdown
    id: disclaimer
    attributes:
      value: |
        ## ⚠️ Disclaimer

        _Thank you for taking the time to create this issue and help_ ``poetry_plugin_constrain``!

        _If you have a question (e.g. how to do something or where to find information), or if you're unsure if your problem is actually a bug, please post your question on the_ [Discussions](https://github.com/adam-grant-hendry/poetry_plugin_constrain/discussions) _tab instead. We are happy to help you there! Another good place to ask is_ [StackOverflow (SO)](https://stackoverflow.com/).

        _Reserving the_ [Issues](https://github.com/adam-grant-hendry/poetry_plugin_constrain) _tab for bugs and feature requests will help us when scheduling time to fix problems and add functionality. This will enable us to solve issues quickly for everyone in the community! That said, don't worry about making a mistake. If you think you're dealing with a bug, post it here and we'll work through it with you. We'd rather know than not know 😉!_

        _Thank you in advance!_

  - type: checkboxes
    id: prerequisites
    attributes:
      label: ✅ Prerequisites
      description: |
        By submitting this issue, I agree to the following:
      options:
        - label: |
            I have reviewed the disclaimer above: I am not submitting a general question and believe this to be an actual bug.
          required: true
        - label: |
            I have read and agree to follow this project's [Code of Conduct](https://example.com). I will treat all people respectfully in communications here.
          required: true
        - label: |
            I have searched the [Issues](https://github.com/adam-grant-hendry/poetry_plugin_constrain) and [Discussions](https://github.com/adam-grant-hendry/poetry_plugin_constrain/discussions) tabs for similar/relevant issues and do not believe this to be a duplicate.
          required: true

  - type: textarea
    id: description
    attributes:
      label: 📜 Description
      description: A clear and concise description of what the bug is
      placeholder: |
        * Explain what you are trying to do (_include a_ `gist` _link, if appropriate._)
        * Add links to documentation and/or examples (_show where you have looked_)
        * Reference related Issues, PRs, Discussions, and/or SO posts (_show where you have looked_)

        Example:
          I am trying to do `xyz`. I am following [this example](https://www.example.com). [The docs here](https://www.docs.com/#page) lead me to believe I can do this, but instead `abc` happens. This has been discussed in [#123](https://www.issue.com), but it hasn't been or resolved or my issue is different because of `123`.
    validations:
      required: true

  - type: textarea
    id: system-information
    attributes:
      label: 🖥️ System Information
      description: |
        Please run the following utility script to generate the system information required to address your bug and paste the output below.
        ```python
        # Print your system information
        from pprint import pprint

        from poetry_plugin_constrain.utilities import system_info

        pprint(system_info())
        ```
      placeholder: |
        The output will be automatically formatted, so you do not need to use backticks here!
      render: shell
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: ℹ️ Steps to Reproduce
      description: Enter the steps to reproduce the problem, including code if relevant.
      placeholder: |
        Please enter the steps you followed in sequential order.  When entering code, please do your best to create a minimal reproducible example ([MRE](https://stackoverflow.com/help/minimal-reproducible-example)):
          * Remove as much code as possible from your source that still produces the bug and add a comment where it occurs
          * Copy and paste the code here (_be sure it runs first!_)
          * If your code is in a package, and knowledge of the files and folder structure is relevant, please show a tree of the structure ([`seedir`](https://github.com/earnestt1234/seedir)) is a great package for this.
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: 🐛 Current Behavior
      description: |
        Enter what happens (the bug), including error messages, logs, screenshots, and GIFs/MP4s.
    validations:
      required: true

  - type: textarea
    id: desired-behavior
    attributes:
      label: 👍 Desired Behavior
      description: |
        Enter what "should" happen. If some documentation indicates what should happen, please add a link to it here.
    validations:
      required: true
