name: Documentation

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-docs:
    permissions:
      contents: write
      pages: write
      id-token: write

    defaults:
      run:
        shell: bash

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache `venv`
        uses: actions/cache@v3
        id: venv-cache
        with:
          path: .venv
          key: ${{ github.workflow }}-${{ github.job }}-venv-${{ matrix.os }}-python${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install `poetry==1.6.1`
        run: pipx install poetry==1.6.1

      - name: Configure `poetry`
        run: poetry config virtualenvs.in-project true

      - name: Install `commitizen==3.9.0`
        run: |
          pipx install commitizen==3.9.0

      - name: Install `python==3.10`
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: "3.10"

      - name: Configure `pip`
        run: python -m pip config set global.disable-pip-version-check true

      - name: Install Dependencies
        if: steps.venv-cache.outputs.cache-hit != 'true'
        run: poetry install --with docs

      - name: Get Project Version
        id: project-version
        run: |
          version="$(cz version --project)"
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Build Docs
        run: |
          if git describe --tags --exact-match >/dev/null 2>&1; then
            export DOCSVERSION=${{ steps.project-version.outputs.version }}
          else
            export DOCSVERSION=main
          fi

          poetry run make -C docs html

          mv "docs/build/${DOCSVERSION}/html" "docs/build/${DOCSVERSION}"
          rm -rf "docs/build/${DOCSVERSION}/html"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/build
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          full_commit_message: ${{ github.event.head_commit.message }}
          keep_files: true
