name: Documentation

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-docs:
    permissions:
      contents: write
      pages: write
      id-token: write

    defaults:
      run:
        shell: bash

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install `poetry==1.6.1`
        run: |
          pipx install poetry==1.6.1

      - name: Install `python==3.10`
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: "3.10"
          cache: 'poetry'

      - name: Configure `pip`
        run: |
          python -m pip config set global.disable-pip-version-check true

      - name: Install Dependencies
        if: steps.setup-python.outputs.cache-hit != 'true'
        run: |
          poetry install --with docs

      - name: Build Docs
        run: |
          poetry run make -C docs html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/_build/html/
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          full_commit_message: ${{ github.event.head_commit.message }}
